apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-portfolio

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: devops-portfolio

  template:
    metadata:
      labels:
        app: devops-portfolio

    spec:
      containers:
        - name: devops-portfolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
